version: '3.1'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    volumes:
      - app_mariadb_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mariadb

volumes:
  app_mariadb_data: